### ISSUE TITLE
I meet AttributeError: __pydantic_core_schema__ when i run web_interactive_demo.py

### ISSUE THREAD

**Issue by hb-jw** [VITA-MLLM/VITA#20]
What should i do to fix this bug?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/vita_demo/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 401, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/opt/conda/envs/vita_demo/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "/opt/conda/envs/vita_demo/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/conda/envs/vita_demo/lib/python3.10/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/conda/envs/vita_demo/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/opt/conda/envs/vita_demo/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/opt/conda/envs/vita_demo/lib/python3.10/site-packages/gradio/route_utils.py", line 766, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/opt/conda/envs/vita_demo/lib/python3.10/site-packages/gradio/route_utils.py", line 782, in simple_response
    await self.app(scope, receive, send)
  File "/opt/conda/envs/vita_demo/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/opt/conda/envs/vita_demo/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/opt/conda/envs/vita_demo/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/opt/conda/envs/vita_demo/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/conda/envs/vita_demo/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/opt/conda/envs/vita_demo/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/opt/conda/envs/vita_demo/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/opt/conda/envs/vita_demo/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/opt/conda/envs/vita_demo/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/opt/conda/envs/vita_demo/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/opt/conda/envs/vita_demo/lib/python3.10/site-packages/fastapi/routing.py", line 291, in app
    solved_result = await solve_dependencies(
  File "/opt/conda/envs/vita_demo/lib/python3.10/site-packages/fastapi/dependencies/utils.py", line 639, in solve_dependencies
    ) = await request_body_to_args(  # body_params checked above
  File "/opt/conda/envs/vita_demo/lib/python3.10/site-packages/fastapi/dependencies/utils.py", line 813, in request_body_to_args
    fields_to_extract = get_model_fields(first_field.type_)
  File "/opt/conda/envs/vita_demo/lib/python3.10/site-packages/fastapi/_compat.py", line 283, in get_model_fields
    return [
  File "/opt/conda/envs/vita_demo/lib/python3.10/site-packages/fastapi/_compat.py", line 284, in <listcomp>
    ModelField(field_info=field_info, name=name)
  File "<string>", line 6, in __init__
  File "/opt/conda/envs/vita_demo/lib/python3.10/site-packages/fastapi/_compat.py", line 109, in __post_init__
    self._type_adapter: TypeAdapter[Any] = TypeAdapter(
  File "/opt/conda/envs/vita_demo/lib/python3.10/site-packages/pydantic/type_adapter.py", line 266, in __init__
    self._init_core_attrs(rebuild_mocks=False)
  File "/opt/conda/envs/vita_demo/lib/python3.10/site-packages/pydantic/type_adapter.py", line 144, in wrapped
    return func(self, *args, **kwargs)
  File "/opt/conda/envs/vita_demo/lib/python3.10/site-packages/pydantic/type_adapter.py", line 286, in _init_core_attrs
    self._core_schema = _get_schema(self._type, config_wrapper, parent_depth=self._parent_depth)
  File "/opt/conda/envs/vita_demo/lib/python3.10/site-packages/pydantic/type_adapter.py", line 104, in _get_schema
    schema = gen.generate_schema(type_)
  File "/opt/conda/envs/vita_demo/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 655, in generate_schema
    schema = self._generate_schema_inner(obj)
  File "/opt/conda/envs/vita_demo/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 908, in _generate_schema_inner
    return self._annotated_schema(obj)
  File "/opt/conda/envs/vita_demo/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 2025, in _annotated_schema
    schema = self._apply_annotations(source_type, annotations)
  File "/opt/conda/envs/vita_demo/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 2104, in _apply_annotations
    schema = get_inner_schema(source_type)
  File "/opt/conda/envs/vita_demo/lib/python3.10/site-packages/pydantic/_internal/_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
  File "/opt/conda/envs/vita_demo/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 2186, in new_handler
    schema = metadata_get_schema(source, get_inner_schema)
  File "/opt/conda/envs/vita_demo/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 2182, in <lambda>
    lambda source, handler: handler(source)
  File "/opt/conda/envs/vita_demo/lib/python3.10/site-packages/pydantic/_internal/_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
  File "/opt/conda/envs/vita_demo/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 2085, in inner_handler
    schema = self._generate_schema_inner(obj)
  File "/opt/conda/envs/vita_demo/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 929, in _generate_schema_inner
    return self.match_type(obj)
  File "/opt/conda/envs/vita_demo/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1029, in match_type
    return self._match_generic_type(obj, origin)
  File "/opt/conda/envs/vita_demo/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1058, in _match_generic_type
    return self._union_schema(obj)
  File "/opt/conda/envs/vita_demo/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1378, in _union_schema
    choices.append(self.generate_schema(arg))
  File "/opt/conda/envs/vita_demo/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 655, in generate_schema
    schema = self._generate_schema_inner(obj)
  File "/opt/conda/envs/vita_demo/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 929, in _generate_schema_inner
    return self.match_type(obj)
  File "/opt/conda/envs/vita_demo/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1038, in match_type
    return self._unknown_type_schema(obj)
  File "/opt/conda/envs/vita_demo/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 558, in _unknown_type_schema
    raise PydanticSchemaGenerationError(
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'starlette.requests.Request'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.

If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.

For further information visit https://errors.pydantic.dev/2.9/u/schema-for-unknown-type
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/opt/conda/envs/vita_demo/lib/python3.10/site-packages/pydantic/type_adapter.py", line 279, in _init_core_attrs
    self._core_schema = _getattr_no_parents(self._type, '__pydantic_core_schema__')
  File "/opt/conda/envs/vita_demo/lib/python3.10/site-packages/pydantic/type_adapter.py", line 121, in _getattr_no_parents
    raise AttributeError(attribute)
AttributeError: __pydantic_core_schema__

**Comment by hb-jw** [comment]
I run the demo on A800,and set the device=2 for LLM1,device=3 for LLM2.

**Comment by longzw1997** [comment]
The occurrence of this bug may be due to package version mismatches. You can refer to this environment to configure your conda environment.

Package                           Version
--------------------------------- ------------
aiofiles                          23.2.1
aiohappyeyeballs                  2.4.0
aiohttp                           3.10.5
aiosignal                         1.3.1
annotated-types                   0.7.0
anyio                             4.4.0
async-timeout                     4.0.3
attrs                             24.2.0
audioread                         3.0.1
certifi                           2024.8.30
cffi                              1.17.1
charset-normalizer                3.3.2
click                             8.1.7
cloudpickle                       3.0.0
coloredlogs                       15.0.1
contourpy                         1.3.0
cycler                            0.12.1
datasets                          2.21.0
decorator                         5.1.1
decord                            0.6.0
dill                              0.3.8
diskcache                         5.6.3
distro                            1.9.0
exceptiongroup                    1.2.2
fastapi                           0.112.2
ffmpeg-python                     0.2.0
ffmpy                             0.4.0
filelock                          3.15.4
flatbuffers                       24.3.25
fonttools                         4.53.1
frozenlist                        1.4.1
fsspec                            2024.6.1
future                            1.0.0
gguf                              0.9.1
gradio                            4.42.0
gradio_client                     1.3.0
h11                               0.14.0
httpcore                          1.0.5
httptools                         0.6.1
httpx                             0.27.2
huggingface-hub                   0.24.6
humanfriendly                     10.0
idna                              3.8
importlib_metadata                8.4.0
importlib_resources               6.4.4
interegular                       0.3.3
Jinja2                            3.1.4
jiter                             0.5.0
joblib                            1.4.2
jsonschema                        4.23.0
jsonschema-specifications         2023.12.1
kiwisolver                        1.4.7
lark                              1.2.2
lazy_loader                       0.4
librosa                           0.10.2.post1
llvmlite                          0.43.0
lm-format-enforcer                0.10.6
markdown-it-py                    3.0.0
MarkupSafe                        2.1.5
matplotlib                        3.9.2
mdurl                             0.1.2
mpmath                            1.3.0
msgpack                           1.0.8
msgspec                           0.18.6
multidict                         6.0.5
multiprocess                      0.70.16
nest-asyncio                      1.6.0
networkx                          3.3
numba                             0.60.0
numpy                             1.26.4
nvidia-cublas-cu12                12.1.3.1
nvidia-cuda-cupti-cu12            12.1.105
nvidia-cuda-nvrtc-cu12            12.1.105
nvidia-cuda-runtime-cu12          12.1.105
nvidia-cudnn-cu12                 9.1.0.70
nvidia-cufft-cu12                 11.0.2.54
nvidia-curand-cu12                10.3.2.106
nvidia-cusolver-cu12              11.4.5.107
nvidia-cusparse-cu12              12.1.0.106
nvidia-ml-py                      12.560.30
nvidia-nccl-cu12                  2.20.5
nvidia-nvjitlink-cu12             12.6.68
nvidia-nvtx-cu12                  12.1.105
onnxruntime                       1.16.3
openai                            1.43.1
opencv-python                     4.10.0.84
orjson                            3.10.7
outlines                          0.0.46
packaging                         24.1
pandas                            2.2.2
pillow                            10.4.0
pip                               24.2
platformdirs                      4.2.2
pooch                             1.8.2
prometheus_client                 0.20.0
prometheus-fastapi-instrumentator 7.0.0
protobuf                          5.28.0
psutil                            6.0.0
py-cpuinfo                        9.0.0
pyairports                        2.1.1
pyarrow                           17.0.0
PyAudio                           0.2.14
pycountry                         24.6.1
pycparser                         2.22
pydantic                          2.8.2
pydantic_core                     2.20.1
pydub                             0.25.1
Pygments                          2.18.0
pyparsing                         3.1.4
python-dateutil                   2.9.0.post0
python-dotenv                     1.0.1
python-multipart                  0.0.9
pytz                              2024.1
PyYAML                            6.0.2
pyzmq                             26.2.0
ray                               2.35.0
referencing                       0.35.1
regex                             2024.7.24
requests                          2.32.3
rich                              13.8.0
rpds-py                           0.20.0
ruff                              0.6.4
safetensors                       0.4.5
scikit-learn                      1.5.1
scipy                             1.14.1
semantic-version                  2.10.0
sentencepiece                     0.2.0
setuptools                        72.1.0
shellingham                       1.5.4
shortuuid                         1.0.13
six                               1.16.0
sniffio                           1.3.1
soundfile                         0.12.1
soxr                              0.5.0.post1
starlette                         0.38.4
sympy                             1.13.2
tencentcloud-sdk-python-common    3.0.1226
tencentcloud-sdk-python-tts       3.0.1226
threadpoolctl                     3.5.0
tiktoken                          0.7.0
tokenizers                        0.19.1
tomlkit                           0.12.0
torch                             2.4.0
torchaudio                        2.4.0
torchvision                       0.19.0
tqdm                              4.66.5
transformers                      4.44.2
triton                            3.0.0
typer                             0.12.5
typing_extensions                 4.12.2
tzdata                            2024.1
urllib3                           2.2.2
uvicorn                           0.30.6
uvloop                            0.20.0
vllm                              0.5.5
vllm-flash-attn                   2.6.1
watchfiles                        0.24.0
websockets                        12.0
wheel                             0.43.0
xformers                          0.0.27.post2
xxhash                            3.5.0
yarl                              1.9.11
zipp                              3.20.1
