### ISSUE TITLE
Web DEMO: ValueError: Unrecognized configuration class to build an AutoTokenizer.

### ISSUE THREAD

**Issue by Kidand** [VITA-MLLM/VITA#28]
When I execute `python -m web_demo.web_ability_demo  demo_VITA_ckpt/ `

The following error occurred:
```bash
Traceback (most recent call last):
  File "/xxx/.conda/envs/vita_demo/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/xxx/.conda/envs/vita_demo/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/xxx/LMM/yanjz/projects/VITA/web_demo/web_ability_demo.py", line 361, in <module>
    main(args.model_path)
  File "/xxx/LMM/yanjz/projects/VITA/web_demo/web_ability_demo.py", line 340, in main
    llm = LLM(
  File "/xxx/.conda/envs/vita_demo/lib/python3.10/site-packages/vllm/entrypoints/llm.py", line 175, in __init__
    self.llm_engine = LLMEngine.from_engine_args(
  File "/xxx/.conda/envs/vita_demo/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 473, in from_engine_args
    engine = cls(
  File "/xxx/.conda/envs/vita_demo/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 247, in __init__
    self.tokenizer = self._init_tokenizer()
  File "/xxx/.conda/envs/vita_demo/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 521, in _init_tokenizer
    return init_tokenizer_from_configs(
  File "/xxx/.conda/envs/vita_demo/lib/python3.10/site-packages/vllm/transformers_utils/tokenizer_group/__init__.py", line 28, in init_tokenizer_from_configs
    return get_tokenizer_group(parallel_config.tokenizer_pool_config,
  File "/xxx/.conda/envs/vita_demo/lib/python3.10/site-packages/vllm/transformers_utils/tokenizer_group/__init__.py", line 49, in get_tokenizer_group
    return tokenizer_cls.from_config(tokenizer_pool_config, **init_kwargs)
  File "/xxx/.conda/envs/vita_demo/lib/python3.10/site-packages/vllm/transformers_utils/tokenizer_group/tokenizer_group.py", line 30, in from_config
    return cls(**init_kwargs)
  File "/xxx/.conda/envs/vita_demo/lib/python3.10/site-packages/vllm/transformers_utils/tokenizer_group/tokenizer_group.py", line 23, in __init__
    self.tokenizer = get_tokenizer(self.tokenizer_id, **tokenizer_config)
  File "/xxx/.conda/envs/vita_demo/lib/python3.10/site-packages/vllm/transformers_utils/tokenizer.py", line 122, in get_tokenizer
    raise e
  File "/xxx/.conda/envs/vita_demo/lib/python3.10/site-packages/vllm/transformers_utils/tokenizer.py", line 103, in get_tokenizer
    tokenizer = AutoTokenizer.from_pretrained(
  File "/xxx/.conda/envs/vita_demo/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 930, in from_pretrained
    raise ValueError(
ValueError: Unrecognized configuration class <class 'transformers_modules.configuration_mixtral_multimodal.MixtralMultiModalConfig'> to build an AutoTokenizer.
Model type should be one of AlbertConfig, AlignConfig, BarkConfig, BartConfig, BertConfig, BertGenerationConfig, BigBirdConfig, BigBirdPegasusConfig, BioGptConfig, BlenderbotConfig, BlenderbotSmallConfig, BlipConfig, Blip2Config, BloomConfig, BridgeTowerConfig, BrosConfig, CamembertConfig, CanineConfig, ChameleonConfig, ChineseCLIPConfig, ClapConfig, CLIPConfig, CLIPSegConfig, ClvpConfig, LlamaConfig, CodeGenConfig, CohereConfig, ConvBertConfig, CpmAntConfig, CTRLConfig, Data2VecAudioConfig, Data2VecTextConfig, DbrxConfig, DebertaConfig, DebertaV2Config, DistilBertConfig, DPRConfig, ElectraConfig, ErnieConfig, ErnieMConfig, EsmConfig, FalconConfig, FalconMambaConfig, FastSpeech2ConformerConfig, FlaubertConfig, FNetConfig, FSMTConfig, FunnelConfig, GemmaConfig, Gemma2Config, GitConfig, GPT2Config, GPT2Config, GPTBigCodeConfig, GPTNeoConfig, GPTNeoXConfig, GPTNeoXJapaneseConfig, GPTJConfig, GPTSanJapaneseConfig, GroundingDinoConfig, GroupViTConfig, HubertConfig, IBertConfig, IdeficsConfig, Idefics2Config, InstructBlipConfig, InstructBlipVideoConfig, JambaConfig, JetMoeConfig, JukeboxConfig, Kosmos2Config, LayoutLMConfig, LayoutLMv2Config, LayoutLMv3Config, LEDConfig, LiltConfig, LlamaConfig, LlavaConfig, LlavaNextConfig, LlavaNextVideoConfig, LongformerConfig, LongT5Config, LukeConfig, LxmertConfig, M2M100Config, MambaConfig, Mamba2Config, MarianConfig, MBartConfig, MegaConfig, MegatronBertConfig, MgpstrConfig, MistralConfig, MixtralConfig, MobileBertConfig, MPNetConfig, MptConfig, MraConfig, MT5Config, MusicgenConfig, MusicgenMelodyConfig, MvpConfig, NezhaConfig, NllbMoeConfig, NystromformerConfig, OlmoConfig, OlmoeConfig, OneFormerConfig, OpenAIGPTConfig, OPTConfig, Owlv2Config, OwlViTConfig, PaliGemmaConfig, PegasusConfig, PegasusXConfig, PerceiverConfig, PersimmonConfig, PhiConfig, Phi3Config, Pix2StructConfig, PLBartConfig, ProphetNetConfig, QDQBertConfig, Qwen2Config, Qwen2AudioConfig, Qwen2MoeConfig, RagConfig, RealmConfig, RecurrentGemmaConfig, ReformerConfig, RemBertConfig, RetriBertConfig, RobertaConfig, RobertaPreLayerNormConfig, RoCBertConfig, RoFormerConfig, RwkvConfig, SeamlessM4TConfig, SeamlessM4Tv2Config, SiglipConfig, Speech2TextConfig, Speech2Text2Config, SpeechT5Config, SplinterConfig, SqueezeBertConfig, StableLmConfig, Starcoder2Config, SwitchTransformersConfig, T5Config, TapasConfig, TransfoXLConfig, TvpConfig, UdopConfig, UMT5Config, VideoLlavaConfig, ViltConfig, VipLlavaConfig, VisualBertConfig, VitsConfig, Wav2Vec2Config, Wav2Vec2BertConfig, Wav2Vec2ConformerConfig, WhisperConfig, XCLIPConfig, XGLMConfig, XLMConfig, XLMProphetNetConfig, XLMRobertaConfig, XLMRobertaXLConfig, XLNetConfig, XmodConfig, YosoConfig.
```
I hope you can provide me with a detailed usage example.

**Comment by longzw1997** [comment]
![WeChatc39cd69c9f5df76dc487d64befb40dc1](https://github.com/user-attachments/assets/6fb7b99b-c538-448b-8eef-1f1befe03902)
In our tests, it loads correctly here. Could you provide more information? For example, the contents of your folder, your environment, etc.

**Comment by Kidand** [comment]
> ![WeChatc39cd69c9f5df76dc487d64befb40dc1](https://private-user-images.githubusercontent.com/85285159/366477668-6fb7b99b-c538-448b-8eef-1f1befe03902.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMDIxMTUsIm5iZiI6MTcyNjEwMTgxNSwicGF0aCI6Ii84NTI4NTE1OS8zNjY0Nzc2NjgtNmZiN2I5OWItYzUzOC00NDhiLThlZWYtMWYxYmVmZTAzOTAyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDAwNDMzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzODA2ZGEwZTcyMTFjZmEzMzdjYWJhODk1OGNkNTNjNWZjYTYwOGFlYTNlYzFiMDQ0YTUzMWEzNWVmNDY4ZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sn3imDYEEIibIuJkKAgBOoo_TGkJFdftgokhj0lUYpo) In our tests, it loads correctly here. Could you provide more information? For example, the contents of your folder, your environment, etc.

```bash
├── asset
│   ├── audio_eval.jpg
│   ├── demo1.jpg
│   ├── demo2.jpg
│   ├── language_eval2.png
│   ├── language_eval.png
│   ├── q1.wav
│   ├── q2.wav
│   ├── visual_eval.jpg
│   ├── VITA_duplex.png
│   ├── VITA_features.png
│   ├── vita_log2.png
│   ├── vita.png
│   └── wechat.jpg
├── command.sh
├── data_tools
│   ├── check_audio_lost.py
│   ├── check_image_lost.py
│   ├── check_image_space_ratio.py
│   ├── check_json.py
│   ├── check_video_lost.py
│   ├── concat_data_frameCat.py
│   ├── concat_data_patch.py
│   ├── concat_data.py
│   ├── rm_lost_audio_in_json.py
│   ├── rm_lost_image_in_json.py
│   ├── rm_lost_video_in_json.py
│   ├── statistics_audio_duration.py
│   ├── statistics_data_num.py
│   ├── statistics_image_num.py
│   ├── statistics_token_num_frameCat.py
│   ├── statistics_token_num_patch.py
│   ├── statistics_token_num_patch_video.py
│   └── statistics_token_num.py
├── demo_VITA_ckpt
│   ├── config.json
│   ├── configuration_intern_vit.py
│   ├── configuration_mixtral_multimodal.py
│   ├── configuration_whale.py
│   ├── feature_extractor
│   │   ├── config.json
│   │   └── preprocessor_config.json
│   ├── generation_config.json -> ../../../blobs/7048d41e7c128f8ea51cfaa7a107aaa7d74bf430
│   ├── model-00001-of-00020.safetensors -> ../../../blobs/63fad60118bd84a5cb88a615529d4e806ce3dd759e365475547d3be466638165
│   ├── model-00002-of-00020.safetensors
│   ├── model-00003-of-00020.safetensors -> ../../../blobs/28c0da42b1d2233ad62d4a007a3d5a746821773be2719e52ec2729443e1edf4e
│   ├── model-00004-of-00020.safetensors -> ../../../blobs/8eb9f328a0527e40225759f3f10e0e638a15fadcb0094074cc7ec45b7de62390
│   ├── model-00005-of-00020.safetensors -> ../../../blobs/72bb9b296503d5579f8ac0ac1a8a4799324f825e6e8dd98cca3094f6a6669b4e
│   ├── model-00006-of-00020.safetensors -> ../../../blobs/d52c05761129aab08f6ad08b799b9745723239738175f39a9f0a1cd56efa6e25
│   ├── model-00007-of-00020.safetensors -> ../../../blobs/e5805558e503272efea6817349bb1a0903482a33ab337628dfa3cadb48337290
│   ├── model-00008-of-00020.safetensors -> ../../../blobs/59fdd1b679761b75303947ba587568c1a768ac40b603077d64d5e99bdf1b4d8e
│   ├── model-00009-of-00020.safetensors -> ../../../blobs/462743b118872c416c597401e40803ddd2a356726dc4b0fa1391cdcd90a4799b
│   ├── model-00010-of-00020.safetensors -> ../../../blobs/026de87b2a843b874fe7856f9278565c58a7388bb0859771dd9511d06a6e09b6
│   ├── model-00011-of-00020.safetensors -> ../../../blobs/28cae79165c3ba203d6f18c6032c9b106bed206393940207d0979cbc35a7c490
│   ├── model-00012-of-00020.safetensors -> ../../../blobs/3dea58b2f8a4546ca40b9a8703c0717c78eb56d6e6ddaef9a24f66a79cdc467c
│   ├── model-00013-of-00020.safetensors -> ../../../blobs/0178d405dad2bcba1132e6b1692cad45ef91a04f51036d0b73c39e0eaa0e4b95
│   ├── model-00014-of-00020.safetensors -> ../../../blobs/2c1f90c7557a7be62f50348e06bcb36a3eccda245e5ab5f302c7bb59c243b238
│   ├── model-00015-of-00020.safetensors -> ../../../blobs/8005e010af9bc0628d66d38c08c22d8ff09477f040b1742b3f99bed0a3e022ce
│   ├── model-00016-of-00020.safetensors -> ../../../blobs/f0d414a060d8ff1ed2c0f81b549425398b487f5e9a69f53951ec16955aeb0b42
│   ├── model-00017-of-00020.safetensors -> ../../../blobs/f7283922bc3c4cc82e0e178acee391ab597fd427635d0a458503c5066df33c37
│   ├── model-00018-of-00020.safetensors -> ../../../blobs/a34557324f874d97f7d704fef308160038551d86f769482c67361da82a91d840
│   ├── model-00019-of-00020.safetensors -> ../../../blobs/c2d9dab4dde8ad094a4ccdbce809649bf1709de856cdf4abb253e34c411e48e7
│   ├── model-00020-of-00020.safetensors -> ../../../blobs/ddede828132858c57d8713f78c24a2e85cfe8eee212ab138b7ed1c8917453f16
│   ├── modeling_intern_vit.py
│   ├── modeling_whale.py
│   ├── model.safetensors.index.json -> ../../../blobs/cffdf98d06dbd5852d64e4e28e36d86dcdd37ec4
│   ├── preprocessor_config.json
│   ├── processor_whale.py
│   ├── __pycache__
│   │   ├── configuration_intern_vit.cpython-310.pyc
│   │   ├── configuration_mixtral_multimodal.cpython-310.pyc
│   │   └── configuration_whale.cpython-310.pyc
│   ├── special_tokens_map.json -> ../../../blobs/622517c23e3f403f563a0827a1c364321e4f9355
│   ├── tokenizer_config.json -> ../../../blobs/22f8b9e319e02131dfeee2e4ead957079817d6f5
│   ├── tokenizer.json -> ../../../blobs/694058c39b1d1c8992b069c2d7e654b4e90d9cdf
│   ├── tokenizer.model
│   ├── training_args.bin -> ../../../blobs/33cb1cafc2b4611cb0e35b38440dfebde0be44e1129186d3d0a6d1d615603630
│   └── zero_to_fp32.py -> ../../../blobs/c5246ff52274e1d6142001ccf085186d3545ce57
├── License.txt
├── mixtral_decode.py
├── mixtral_inference.py
├── README.md
├── requirements.txt
├── script
│   ├── deepspeed
│   │   ├── ds_config_zero3.json
│   │   ├── ds_config_zero3_offload2.json
│   │   ├── ds_config_zero3_offload.json
│   │   ├── zero2.json
│   │   └── zero3.json
│   ├── merge_lora_weights.py
│   └── train
│       ├── finetune_nodes.sh
│       ├── finetune.sh
│       ├── finetuneTask_nodes.sh
│       ├── pretrain_mlp_nodes.sh
│       └── pretrain_mlp.sh
├── video_audio_demo.py
├── vita
│   ├── config
│   │   ├── dataset_config.py
│   │   ├── __init__.py
│   │   └── __pycache__
│   │       ├── dataset_config.cpython-310.pyc
│   │       └── __init__.cpython-310.pyc
│   ├── constants.py
│   ├── conversation.py
│   ├── model
│   │   ├── builder.py
│   │   ├── __init__.py
│   │   ├── language_model
│   │   │   ├── __pycache__
│   │   │   │   └── vita_mixtral.cpython-310.pyc
│   │   │   └── vita_mixtral.py
│   │   ├── multimodal_encoder
│   │   │   ├── builder.py
│   │   │   ├── clip
│   │   │   │   ├── clip_encoder.py
│   │   │   │   └── __pycache__
│   │   │   │       └── clip_encoder.cpython-310.pyc
│   │   │   ├── eva_clip
│   │   │   │   ├── eva_clip_encoder.py
│   │   │   │   ├── eva_clip_processors.py
│   │   │   │   ├── eva_vit.py
│   │   │   │   └── __pycache__
│   │   │   │       ├── eva_clip_encoder.cpython-310.pyc
│   │   │   │       ├── eva_clip_processors.cpython-310.pyc
│   │   │   │       └── eva_vit.cpython-310.pyc
│   │   │   ├── internvit
│   │   │   │   ├── configuration_intern_vit.py
│   │   │   │   ├── flash_attention.py
│   │   │   │   ├── internvit_encoder.py
│   │   │   │   ├── modeling_intern_vit.py
│   │   │   │   └── __pycache__
│   │   │   │       ├── configuration_intern_vit.cpython-310.pyc
│   │   │   │       ├── flash_attention.cpython-310.pyc
│   │   │   │       ├── internvit_encoder.cpython-310.pyc
│   │   │   │       └── modeling_intern_vit.cpython-310.pyc
│   │   │   ├── __pycache__
│   │   │   │   └── builder.cpython-310.pyc
│   │   │   ├── siglip
│   │   │   │   ├── __pycache__
│   │   │   │   │   └── siglip_encoder.cpython-310.pyc
│   │   │   │   └── siglip_encoder.py
│   │   │   └── whale
│   │   │       ├── adapter.py
│   │   │       ├── cmvn.py
│   │   │       ├── init_model.py
│   │   │       ├── module
│   │   │       │   ├── component
│   │   │       │   │   ├── mamba.py
│   │   │       │   │   ├── __pycache__
│   │   │       │   │   │   ├── mamba.cpython-310.pyc
│   │   │       │   │   │   ├── subsampling.cpython-310.pyc
│   │   │       │   │   │   └── transformer.cpython-310.pyc
│   │   │       │   │   ├── subsampling.py
│   │   │       │   │   └── transformer.py
│   │   │       │   ├── encoder
│   │   │       │   │   ├── encoder.py
│   │   │       │   │   └── __pycache__
│   │   │       │   │       └── encoder.cpython-310.pyc
│   │   │       │   └── layer
│   │   │       │       ├── attention.py
│   │   │       │       ├── conv1d.py
│   │   │       │       ├── dtcblock.py
│   │   │       │       ├── fsmn.py
│   │   │       │       └── __pycache__
│   │   │       │           └── attention.cpython-310.pyc
│   │   │       ├── __pycache__
│   │   │       │   ├── adapter.cpython-310.pyc
│   │   │       │   ├── cmvn.cpython-310.pyc
│   │   │       │   ├── init_model.cpython-310.pyc
│   │   │       │   └── utils.cpython-310.pyc
│   │   │       └── utils.py
│   │   ├── multimodal_projector
│   │   │   ├── builder.py
│   │   │   └── __pycache__
│   │   │       └── builder.cpython-310.pyc
│   │   ├── __pycache__
│   │   │   ├── builder.cpython-310.pyc
│   │   │   ├── __init__.cpython-310.pyc
│   │   │   └── vita_arch.cpython-310.pyc
│   │   └── vita_arch.py
│   ├── __pycache__
│   │   ├── constants.cpython-310.pyc
│   │   └── conversation.cpython-310.pyc
│   ├── train
│   │   ├── train.py
│   │   └── vita_trainer.py
│   └── util
│       ├── data_utils_video_audio_neg_frameCat.py
│       ├── data_utils_video_audio_neg_patch.py
│       ├── data_utils_video_audio.py
│       ├── mm_utils.py
│       ├── __pycache__
│       │   ├── data_utils_video_audio_neg_patch.cpython-310.pyc
│       │   ├── mm_utils.cpython-310.pyc
│       │   └── utils.cpython-310.pyc
│       ├── s2wrapper
│       │   ├── core.py
│       │   ├── __init__.py
│       │   ├── __pycache__
│       │   │   ├── core.cpython-310.pyc
│       │   │   ├── __init__.cpython-310.pyc
│       │   │   └── utils.cpython-310.pyc
│       │   └── utils.py
│       └── utils.py
└── web_demo
    ├── __pycache__
    │   ├── web_ability_demo.cpython-310.pyc
    │   ├── web_ability_demo.cpython-38.pyc
    │   └── web_interactive_demo.cpython-310.pyc
    ├── vllm_tools
    │   ├── model_weight_file
    │   │   ├── config.json
    │   │   ├── configuration_intern_vit.py
    │   │   ├── configuration_mixtral_multimodal.py
    │   │   ├── configuration_whale.py
    │   │   ├── feature_extractor
    │   │   │   ├── config.json
    │   │   │   └── preprocessor_config.json
    │   │   ├── modeling_intern_vit.py
    │   │   ├── modeling_whale.py
    │   │   ├── preprocessor_config.json
    │   │   └── processor_whale.py
    │   └── vllm_file
    │       ├── __init__.py
    │       ├── mixtral.py
    │       └── whale.py
    ├── wakeup_and_vad
    │   ├── __pycache__
    │   │   └── wakeup_and_vad.cpython-310.pyc
    │   ├── resource
    │   │   ├── silero_vad.jit
    │   │   └── silero_vad.onnx
    │   └── wakeup_and_vad.py
    ├── web_ability_demo.py
    ├── web_demo_requirements.txt
    └── web_interactive_demo.py
```
This is my project structure, executed according to the project's `README`. I noticed there are steps involving replacing the model's `config.json` and adding new files to the `vllm` package. Did I use the wrong path for these replacements?

**Comment by longzw1997** [comment]
If the file is correctly overwritten, it should look fine. What is your conda env?

**Comment by Kidand** [comment]
> If the file is correctly overwritten, it should look fine. What is your conda env?

```bash
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
aiofiles                  23.2.1                   pypi_0    pypi
aiohappyeyeballs          2.4.0                    pypi_0    pypi
aiohttp                   3.10.5                   pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
alsa-lib                  1.2.12               h4ab18f5_0    conda-forge
annotated-types           0.7.0                    pypi_0    pypi
anyio                     4.4.0                    pypi_0    pypi
async-timeout             4.0.3                    pypi_0    pypi
attrs                     24.2.0                   pypi_0    pypi
audioread                 3.0.1                    pypi_0    pypi
bzip2                     1.0.8                h4bc722e_7    conda-forge
ca-certificates           2024.8.30            hbcca054_0    conda-forge
certifi                   2024.8.30                pypi_0    pypi
cffi                      1.17.1                   pypi_0    pypi
charset-normalizer        3.3.2                    pypi_0    pypi
click                     8.1.7                    pypi_0    pypi
cloudpickle               3.0.0                    pypi_0    pypi
coloredlogs               15.0.1                   pypi_0    pypi
contourpy                 1.3.0                    pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
datasets                  2.21.0                   pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
decord                    0.6.0                    pypi_0    pypi
dill                      0.3.8                    pypi_0    pypi
diskcache                 5.6.3                    pypi_0    pypi
distro                    1.9.0                    pypi_0    pypi
exceptiongroup            1.2.2                    pypi_0    pypi
fastapi                   0.112.2                  pypi_0    pypi
ffmpeg-python             0.2.0                    pypi_0    pypi
ffmpy                     0.4.0                    pypi_0    pypi
filelock                  3.16.0                   pypi_0    pypi
flatbuffers               24.3.25                  pypi_0    pypi
fonttools                 4.53.1                   pypi_0    pypi
frozenlist                1.4.1                    pypi_0    pypi
fsspec                    2024.6.1                 pypi_0    pypi
future                    1.0.0                    pypi_0    pypi
gguf                      0.9.1                    pypi_0    pypi
gradio                    4.42.0                   pypi_0    pypi
gradio-client             1.3.0                    pypi_0    pypi
h11                       0.14.0                   pypi_0    pypi
httpcore                  1.0.5                    pypi_0    pypi
httptools                 0.6.1                    pypi_0    pypi
httpx                     0.27.2                   pypi_0    pypi
huggingface-hub           0.24.6                   pypi_0    pypi
humanfriendly             10.0                     pypi_0    pypi
idna                      3.8                      pypi_0    pypi
importlib-metadata        8.4.0                    pypi_0    pypi
importlib-resources       6.4.5                    pypi_0    pypi
interegular               0.3.3                    pypi_0    pypi
jinja2                    3.1.4                    pypi_0    pypi
jiter                     0.5.0                    pypi_0    pypi
joblib                    1.4.2                    pypi_0    pypi
jsonschema                4.23.0                   pypi_0    pypi
jsonschema-specifications 2023.12.1                pypi_0    pypi
kiwisolver                1.4.7                    pypi_0    pypi
lark                      1.2.2                    pypi_0    pypi
lazy-loader               0.4                      pypi_0    pypi
ld_impl_linux-64          2.40                 hf3520f5_7    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc                    14.1.0               h77fa898_1    conda-forge
libgcc-ng                 14.1.0               h69a702a_1    conda-forge
libgomp                   14.1.0               h77fa898_1    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
librosa                   0.10.2.post1             pypi_0    pypi
libsqlite                 3.46.1               hadc24fc_0    conda-forge
libstdcxx                 14.1.0               hc0a3c3a_1    conda-forge
libstdcxx-ng              14.1.0               h4852527_1    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libzlib                   1.3.1                h4ab18f5_1    conda-forge
llvmlite                  0.43.0                   pypi_0    pypi
lm-format-enforcer        0.10.6                   pypi_0    pypi
markdown-it-py            3.0.0                    pypi_0    pypi
markupsafe                2.1.5                    pypi_0    pypi
matplotlib                3.9.2                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
mpmath                    1.3.0                    pypi_0    pypi
msgpack                   1.1.0                    pypi_0    pypi
msgspec                   0.18.6                   pypi_0    pypi
multidict                 6.1.0                    pypi_0    pypi
multiprocess              0.70.16                  pypi_0    pypi
ncurses                   6.5                  he02047a_1    conda-forge
nest-asyncio              1.6.0                    pypi_0    pypi
networkx                  3.3                      pypi_0    pypi
numba                     0.60.0                   pypi_0    pypi
numpy                     1.26.4                   pypi_0    pypi
nvidia-cublas-cu12        12.1.3.1                 pypi_0    pypi
nvidia-cuda-cupti-cu12    12.1.105                 pypi_0    pypi
nvidia-cuda-nvrtc-cu12    12.1.105                 pypi_0    pypi
nvidia-cuda-runtime-cu12  12.1.105                 pypi_0    pypi
nvidia-cudnn-cu12         9.1.0.70                 pypi_0    pypi
nvidia-cufft-cu12         11.0.2.54                pypi_0    pypi
nvidia-curand-cu12        10.3.2.106               pypi_0    pypi
nvidia-cusolver-cu12      11.4.5.107               pypi_0    pypi
nvidia-cusparse-cu12      12.1.0.106               pypi_0    pypi
nvidia-ml-py              12.560.30                pypi_0    pypi
nvidia-nccl-cu12          2.20.5                   pypi_0    pypi
nvidia-nvjitlink-cu12     12.6.68                  pypi_0    pypi
nvidia-nvtx-cu12          12.1.105                 pypi_0    pypi
onnxruntime               1.16.3                   pypi_0    pypi
openai                    1.44.1                   pypi_0    pypi
opencv-python             4.10.0.84                pypi_0    pypi
openssl                   3.3.2                hb9d3cd8_0    conda-forge
orjson                    3.10.7                   pypi_0    pypi
outlines                  0.0.46                   pypi_0    pypi
packaging                 24.1                     pypi_0    pypi
pandas                    2.2.2                    pypi_0    pypi
pillow                    10.4.0                   pypi_0    pypi
pip                       24.2               pyh8b19718_1    conda-forge
platformdirs              4.3.2                    pypi_0    pypi
pooch                     1.8.2                    pypi_0    pypi
portaudio                 19.6.0               h7c63dc7_9    conda-forge
prometheus-client         0.20.0                   pypi_0    pypi
prometheus-fastapi-instrumentator 7.0.0                    pypi_0    pypi
protobuf                  5.28.0                   pypi_0    pypi
psutil                    6.0.0                    pypi_0    pypi
py-cpuinfo                9.0.0                    pypi_0    pypi
pyairports                2.1.1                    pypi_0    pypi
pyarrow                   17.0.0                   pypi_0    pypi
pyaudio                   0.2.14                   pypi_0    pypi
pycountry                 24.6.1                   pypi_0    pypi
pycparser                 2.22                     pypi_0    pypi
pydantic                  2.8.2                    pypi_0    pypi
pydantic-core             2.20.1                   pypi_0    pypi
pydub                     0.25.1                   pypi_0    pypi
pygments                  2.18.0                   pypi_0    pypi
pyparsing                 3.1.4                    pypi_0    pypi
python                    3.10.0          h543edf9_3_cpython    conda-forge
python-dateutil           2.9.0.post0              pypi_0    pypi
python-dotenv             1.0.1                    pypi_0    pypi
python-multipart          0.0.9                    pypi_0    pypi
pytz                      2024.2                   pypi_0    pypi
pyyaml                    6.0.2                    pypi_0    pypi
pyzmq                     26.2.0                   pypi_0    pypi
ray                       2.35.0                   pypi_0    pypi
readline                  8.2                  h8228510_1    conda-forge
referencing               0.35.1                   pypi_0    pypi
regex                     2024.7.24                pypi_0    pypi
requests                  2.32.3                   pypi_0    pypi
rich                      13.8.1                   pypi_0    pypi
rpds-py                   0.20.0                   pypi_0    pypi
ruff                      0.6.4                    pypi_0    pypi
safetensors               0.4.5                    pypi_0    pypi
scikit-learn              1.5.1                    pypi_0    pypi
scipy                     1.14.1                   pypi_0    pypi
semantic-version          2.10.0                   pypi_0    pypi
sentencepiece             0.2.0                    pypi_0    pypi
setuptools                73.0.1             pyhd8ed1ab_0    conda-forge
shellingham               1.5.4                    pypi_0    pypi
shortuuid                 1.0.13                   pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
sniffio                   1.3.1                    pypi_0    pypi
soundfile                 0.12.1                   pypi_0    pypi
soxr                      0.5.0.post1              pypi_0    pypi
sqlite                    3.46.1               h9eae976_0    conda-forge
starlette                 0.38.5                   pypi_0    pypi
sympy                     1.13.2                   pypi_0    pypi
tencentcloud-sdk-python-common 3.0.1229                 pypi_0    pypi
tencentcloud-sdk-python-tts 3.0.1229                 pypi_0    pypi
threadpoolctl             3.5.0                    pypi_0    pypi
tiktoken                  0.7.0                    pypi_0    pypi
tk                        8.6.13          noxft_h4845f30_101    conda-forge
tokenizers                0.19.1                   pypi_0    pypi
tomlkit                   0.12.0                   pypi_0    pypi
torch                     2.4.0                    pypi_0    pypi
torchaudio                2.4.0                    pypi_0    pypi
torchvision               0.19.0                   pypi_0    pypi
tqdm                      4.66.5                   pypi_0    pypi
transformers              4.45.0.dev0              pypi_0    pypi
triton                    3.0.0                    pypi_0    pypi
typer                     0.12.5                   pypi_0    pypi
typing-extensions         4.12.2                   pypi_0    pypi
tzdata                    2024.1                   pypi_0    pypi
urllib3                   2.2.2                    pypi_0    pypi
uvicorn                   0.30.6                   pypi_0    pypi
uvloop                    0.20.0                   pypi_0    pypi
vllm                      0.5.5                    pypi_0    pypi
vllm-flash-attn           2.6.1                    pypi_0    pypi
watchfiles                0.24.0                   pypi_0    pypi
websockets                12.0                     pypi_0    pypi
wheel                     0.44.0             pyhd8ed1ab_0    conda-forge
xformers                  0.0.27.post2             pypi_0    pypi
xxhash                    3.5.0                    pypi_0    pypi
xz                        5.2.6                h166bdaf_0    conda-forge
yarl                      1.11.1                   pypi_0    pypi
zipp                      3.20.1                   pypi_0    pypi
```
I followed the README exactly：
```bash
conda create -n vita_demo python==3.10
conda activate vita_demo
pip install -r web_demo/web_demo_requirements.txt
```

**Comment by Kidand** [comment]
After trying, the issue was resolved by deep copying the model.

**Comment by learn01one** [comment]
> After trying, the issue was resolved by deep copying the model.

hello,can you give  some advice,how to solve the issue?how to understand that deep copying the model?

**Comment by Kidand** [comment]
> > After trying, the issue was resolved by deep copying the model.
> 
> hello,can you give some advice,how to solve the issue?how to understand that deep copying the model?

you can try `cp -L` to copy weights
