### ISSUE TITLE
What prompts are used for the audio capacity evaluation?

### ISSUE THREAD

**Issue by Danield21** [VITA-MLLM/VITA#29]
Hi! Thanks for your amazing work!

I am reproducing VITA's evaluation results on WenetSpeech (test_meeting). But when I used the chat-template prompt like：
```python
else: # video_path / image_path is None
                image_tensor = torch.zeros((1, 3, 448, 448)).to(dtype=model.dtype, device="cuda")
                if audio_path:
                    qs = qs + DEFAULT_AUDIO_TOKEN # qs = '<audio>'
                modality = "lang"

conv = conv_templates[conv_mode].copy() # conv_mode = mixtral_two
conv.append_message(conv.roles[0], qs)
conv.append_message(conv.roles[1], None)
prompt = conv.get_prompt(modality)

```
I found the model's response looks pretty weird like:
```Python
gt: 咱们的第八层是属于租的人家的
response: <1>在法律上房屋的所有权通常属于房屋的购买者即房屋的所有者然而房屋的第八层是否属于租住人员这取决于房屋的租赁协议和当地的法律在一些租赁协议中房屋的所有者可能会保留房屋的某些部分例如屋顶、地下室或车库等而其他部分则可以租给租户使用在这种情况下房屋的第八层可能属于租住人员因为它是租户可以使用的部分然而在其他租赁协议中房屋的所有者可能会保留房屋的所有部分而租户只能使用房屋的一部分在这种情况下房屋的第八层可能不属于租住人员因为它是房屋所有者的财产因此房屋的第八层是否属于租住人员需要根据房屋的租赁协议和当地的法律来确定
```
Also, when I inferred the second instance, I got an error:
```Python
Traceback (most recent call last):
  File "/data_train2/data_train/mllm/dingbowen/VITA/video_audio_demo.py", line 609, in <module>
    output_ids = model.generate(
  File "/data_train2/mllm/conda/envs/vita/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data_train2/mllm/conda/envs/vita/lib/python3.10/site-packages/transformers/generation/utils.py", line 1758, in generate
    result = self._sample(
  File "/data_train2/mllm/conda/envs/vita/lib/python3.10/site-packages/transformers/generation/utils.py", line 2397, in _sample
    outputs = self(
  File "/data_train2/mllm/conda/envs/vita/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data_train2/mllm/conda/envs/vita/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data_train2/mllm/conda/envs/vita/lib/python3.10/site-packages/accelerate/hooks.py", line 166, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/data_train2/data_train/mllm/dingbowen/VITA/vita/model/language_model/vita_mixtral.py", line 273, in forward
    ) = self.prepare_inputs_labels_for_multimodal(
  File "/data_train2/data_train/mllm/dingbowen/VITA/vita/model/vita_arch.py", line 233, in prepare_inputs_labels_for_multimodal
    sum([(cur == AUDIO_TOKEN_INDEX).sum() for cur in input_ids])
AssertionError

```

Then I printed the prompt and the input_ids for checking:
```
if audio_path:
    # manual_prompt = prompt_text + DEFAULT_AUDIO_TOKEN 
    # print('prompt', manual_prompt)
    # prompt = manual_prompt
    print(prompt)
    input_ids = (
        tokenizer_image_audio_token(prompt, tokenizer, IMAGE_TOKEN_INDEX, return_tensors="pt")
        .unsqueeze(0)
        .cuda()
    )
    print(input_ids)
    print(input_ids.shape)
```
Then I got
```Python
system:You are an AI robot and your name is VITA. 
- You are a multimodal large language model developed by the open source community. Your aim is to be helpful, honest and harmless. 
- You support the ability to communicate fluently and answer user questions in multiple languages of the user's choice. 
- If the user corrects the wrong answer you generated, you will apologize and discuss the correct answer with the user.</s>
user:<audio></s>
bot:
tensor([[    1,  1587, 28747,  1976,   460,   396, 16107, 18401,   304,   574,
          1141,   349,   550,  1153, 28741, 28723, 28705,    13, 28733,   995,
           460,   264,  2531,   321,   350,   282,  2475,  3842,  2229,  6202,
           486,   272,  1565,  2832,  3618, 28723,  3604,  6503,   349,   298,
           347, 10865, 28725,  6858,   304,  6241,  1503, 28723, 28705,    13,
         28733,   995,  1760,   272,  5537,   298, 16287, 13857,  2250,   304,
          4372,  2188,  4224,   297,  5166, 14028,   302,   272,  2188, 28742,
         28713,  4782, 28723, 28705,    13, 28733,  1047,   272,  2188,  4714,
         28713,   272,  3544,  4372,   368,  7138, 28725,   368,   622, 15884,
           653,   304,  3342,   272,  4714,  4372,   395,   272,  2188, 28723,
             2, 28705,    13,  1838, 28747,  -500,     2, 28705,    13, 10093,
         28747]], device='cuda:0')
torch.Size([1, 111])
gt: 咱们的第八层是属于租的人家的
response: <1>在法律上房屋的所有权通常属于房屋的购买者即房屋的所有者然而房屋的第八层是否属于租住人员这取决于房屋的租赁协议和当地的法律在一些租赁协议中房屋的所有者可能会保留房屋的某些部分例如屋顶、地下室或车库等而其他部分则可以租给租户使用在这种情况下房屋的第八层可能属于租住人员因为它是租户可以使用的部分然而在其他租赁协议中房屋的所有者可能会保留房屋的所有部分而租户只能使用房屋的一部分在这种情况下房屋的第八层可能不属于租住人员因为它是房屋所有者的财产因此房屋的第八层是否属于租住人员需要根据房屋的租赁协议和当地的法律来确定
--------------------------------
Time consume: 24.011798620224
system:You are an AI robot and your name is VITA. 
- You are a multimodal large language model developed by the open source community. Your aim is to be helpful, honest and harmless. 
- You support the ability to communicate fluently and answer user questions in multiple languages of the user's choice. 
- If the user corrects the wrong answer you generated, you will apologize and discuss the correct answer with the user.</s>
user:<audio><audio></s>
bot:
tensor([[    1,  1587, 28747,  1976,   460,   396, 16107, 18401,   304,   574,
          1141,   349,   550,  1153, 28741, 28723, 28705,    13, 28733,   995,
           460,   264,  2531,   321,   350,   282,  2475,  3842,  2229,  6202,
           486,   272,  1565,  2832,  3618, 28723,  3604,  6503,   349,   298,
           347, 10865, 28725,  6858,   304,  6241,  1503, 28723, 28705,    13,
         28733,   995,  1760,   272,  5537,   298, 16287, 13857,  2250,   304,
          4372,  2188,  4224,   297,  5166, 14028,   302,   272,  2188, 28742,
         28713,  4782, 28723, 28705,    13, 28733,  1047,   272,  2188,  4714,
         28713,   272,  3544,  4372,   368,  7138, 28725,   368,   622, 15884,
           653,   304,  3342,   272,  4714,  4372,   395,   272,  2188, 28723,
             2, 28705,    13,  1838, 28747,  -500,  -500,     2, 28705,    13,
         10093, 28747]], device='cuda:0')
torch.Size([1, 112])

```
About configuration, I only modified the audio-path, and kept the remaining args as the default
```Python
# Add arguments
    parser.add_argument("--model_path", type=str, required=True, help="Path to the model directory")
    parser.add_argument("--model_base", type=str, default=None)
    parser.add_argument("--video_path", type=str, default=None)
    parser.add_argument("--image_path", type=str, default=None)
    parser.add_argument("--audio_path", type=str, default=None)
    parser.add_argument("--model_type", type=str, default="mixtral-8x7b")
    parser.add_argument("--conv_mode", type=str, default="mixtral_two")
    parser.add_argument("--question", type=str, default="")
```
Could you please tell me what I did wrong？

Many thanks！

**Comment by BradyFU** [comment]
Hi, the audio capacity evaluation is done after audio alignment in Stage II. 
In the final SFT model (we only release this ckpt by now), we do not perform the audio capacity evaluation, because the audio alignment data (include the prompt) are not used.

**Comment by Danield21** [comment]
> Hi, the audio capacity evaluation is done after audio alignment in Stage II. In the final SFT model (we only release this ckpt by now), we do not perform the audio capacity evaluation, because the audio alignment data (include the prompt) are not used.

I see, thanks for the reply！
may I ask if you plan to release the checkpoint with audio alignment in Stage II later on?

**Comment by BradyFU** [comment]
Yep, I will release the ckpt of audio alignment stage in the next version. Stay tuned！

**Comment by Danield21** [comment]
> Yep, I will release the ckpt of audio alignment stage in the next version. Stay tuned！

Cool, looking forward to that!
