### ISSUE TITLE
Fail to run video_audio_demo.py with ValueError

### ISSUE THREAD

**Issue by superobk** [VITA-MLLM/VITA#43]
As titled, I installed all the packages as well as flash_attn following "Training" instructions.
However, when trying to run video_audio_demo, it will trigger the errors as below.
It is any package still need to be installed or updated? Please kindly advise. Thanks!

> root@bo-deployment-work-68c488599-r4qrz:/Code/VITA# CUDA_VISIBLE_DEVICES=0,1 python video_audio_demo.py     --model_path /Model/Weight/VITA-MLLM/VITA/models--VITA-MLLM--VITA/VITA_ckpt/     --image_path asset/vita_log2.png     --model_type mixtral-8x7b     --conv_mode mixtral_two     --question "请描述这张图片。"
> **Please build and install Nvidia apex package with option '--cuda_ext' according to https://github.com/NVIDIA/apex#from-source .
> Please install mamba_ssm to use MambaSSM component.**
> /usr/local/lib/python3.10/dist-packages/torch/_jit_internal.py:739: FutureWarning: ignore(True) has been deprecated. TorchScript will now drop the function call on compilation. Use torch.jit.unused now. {}
>   warnings.warn(
> Traceback (most recent call last):
>   File "/Code/VITA/video_audio_demo.py", line 163, in <module>
>     tokenizer, model, image_processor, context_len = load_pretrained_model(
>   File "/Code/VITA/vita/model/builder.py", line 219, in load_pretrained_model
>     tokenizer = AutoTokenizer.from_pretrained(model_path, use_fast=True)
>   File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/tokenization_auto.py", line 880, in from_pretrained
>     return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
>   File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py", line 2110, in from_pretrained
>     return cls._from_pretrained(
>   File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py", line 2336, in _from_pretrained
>     tokenizer = cls(*init_inputs, **init_kwargs)
>   File "/usr/local/lib/python3.10/dist-packages/transformers/models/llama/tokenization_llama_fast.py", line 156, in __init__
>     super().__init__(
>   File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_fast.py", line 105, in __init__
>     raise ValueError(
> **ValueError: Cannot instantiate this tokenizer from a slow version. If it's based on sentencepiece, make sure you have sentencepiece installed.**
>

**Comment by superobk** [comment]
> > Hi @superobk , modify the`mm_vision_tower ` in the [config.json](https://huggingface.co/VITA-MLLM/VITA/blob/main/VITA_ckpt/config.json).
> 
> hello,how can we modify the mm_vision_tower?local path?thanks~

The .config.json is in the folder VITA_ckpt, you need to change both "mm_audio_encoder" and "mm_vision_tower" to your local path
