### ISSUE TITLE
RuntimeError: The size of tensor a (56640) must match the size of tensor b (80) at non-singleton dimension 2

### ISSUE THREAD

**Issue by sankexin** [VITA-MLLM/VITA#56]
python video_audio_demo.py --model_path VITA/VITA_ckpt --image_path asset/vita_log2.png --model_type mixtral-8x7b --conv_mode mixtral_two --audio_path asset/q1.wav

Traceback (most recent call last):
  File "/home/VITA/video_audio_demo.py", line 259, in <module>
    output_ids = model.generate(
  File "/usr/local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/transformers/generation/utils.py", line 1758, in generate
    result = self._sample(
  File "/usr/local/lib/python3.10/site-packages/transformers/generation/utils.py", line 2397, in _sample
    outputs = self(
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/accelerate/hooks.py", line 166, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/VITA/vita/model/language_model/vita_mixtral.py", line 273, in forward
    ) = self.prepare_inputs_labels_for_multimodal(
  File "/home/VITA/vita/model/vita_arch.py", line 189, in prepare_inputs_labels_for_multimodal
    audio_features = audio_encoder(audios["audios"], audios["lengths"])
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/accelerate/hooks.py", line 166, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/VITA/vita/model/multimodal_encoder/whale/init_model.py", line 124, in forward
    encoder_out, encoder_mask = self.encoder(speech, speech_lengths)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/accelerate/hooks.py", line 166, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/VITA/vita/model/multimodal_encoder/whale/module/encoder/encoder.py", line 144, in forward
    xs = self.global_cmvn(xs)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/accelerate/hooks.py", line 166, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/VITA/vita/model/multimodal_encoder/whale/cmvn.py", line 29, in forward
    x = x - self.mean
RuntimeError: The size of tensor a (56640) must match the size of tensor b (80) at non-singleton dimension 2

**Comment by sankexin** [comment]
> python video_audio_demo.py --model_path VITA/VITA_ckpt --image_path asset/vita_log2.png --model_type mixtral-8x7b --conv_mode mixtral_two --audio_path asset/q1.wav
> 
> Traceback (most recent call last): File "/home/VITA/video_audio_demo.py", line 259, in output_ids = model.generate( File "/usr/local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context return func(*args, **kwargs) File "/usr/local/lib/python3.10/site-packages/transformers/generation/utils.py", line 1758, in generate result = self._sample( File "/usr/local/lib/python3.10/site-packages/transformers/generation/utils.py", line 2397, in _sample outputs = self( File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl return forward_call(*args, **kwargs) File "/usr/local/lib/python3.10/site-packages/accelerate/hooks.py", line 166, in new_forward output = module._old_forward(*args, **kwargs) File "/home/VITA/vita/model/language_model/vita_mixtral.py", line 273, in forward ) = self.prepare_inputs_labels_for_multimodal( File "/home/VITA/vita/model/vita_arch.py", line 189, in prepare_inputs_labels_for_multimodal audio_features = audio_encoder(audios["audios"], audios["lengths"]) File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl return forward_call(*args, **kwargs) File "/usr/local/lib/python3.10/site-packages/accelerate/hooks.py", line 166, in new_forward output = module._old_forward(*args, **kwargs) File "/home/VITA/vita/model/multimodal_encoder/whale/init_model.py", line 124, in forward encoder_out, encoder_mask = self.encoder(speech, speech_lengths) File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl return forward_call(*args, **kwargs) File "/usr/local/lib/python3.10/site-packages/accelerate/hooks.py", line 166, in new_forward output = module._old_forward(*args, **kwargs) File "/home/VITA/vita/model/multimodal_encoder/whale/module/encoder/encoder.py", line 144, in forward xs = self.global_cmvn(xs) File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl return forward_call(*args, **kwargs) File "/usr/local/lib/python3.10/site-packages/accelerate/hooks.py", line 166, in new_forward output = module._old_forward(*args, **kwargs) File "/home/VITA/vita/model/multimodal_encoder/whale/cmvn.py", line 29, in forward x = x - self.mean RuntimeError: The size of tensor a (56640) must match the size of tensor b (80) at non-singleton dimension 2

This is an error caused by soundfile replacing torchauudio
