### ISSUE TITLE
QuickStart 报错：KeyError: 'cache_position'

### ISSUE THREAD

**Issue by lwj2001** [VITA-MLLM/VITA#62]
```
the number of whale encoder params: 341.3681640625M
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:07<00:00,  1.77s/it]
the number of vision encoder params: 289.9287109375M
```
模型已经加载完毕，推理报错：
```
Traceback (most recent call last):
  File "/Data3/liwenjie/VITA/video_audio_demo.py", line 267, in <module>
    output_ids = model.generate(
  File "/Data1/home/fanziqi/.conda/envs/VITA/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Data3/liwenjie/VITA/vita/model/language_model/vita_qwen2.py", line 221, in generate
    return super().generate(
  File "/Data1/home/fanziqi/.conda/envs/VITA/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Data1/home/fanziqi/.conda/envs/VITA/lib/python3.10/site-packages/transformers/generation/utils.py", line 1758, in generate
    result = self._sample(
  File "/Data1/home/fanziqi/.conda/envs/VITA/lib/python3.10/site-packages/transformers/generation/utils.py", line 2394, in _sample
    model_inputs = self.prepare_inputs_for_generation(input_ids, **model_kwargs)
  File "/Data3/liwenjie/VITA/vita/model/language_model/vita_qwen2.py", line 250, in prepare_inputs_for_generation
    cache_position = _inputs["cache_position"]
KeyError: 'cache_position'
```

**Comment by salixc** [comment]
+1

**Comment by dh888222** [comment]
+1

**Comment by kejun1** [comment]
I have the same problem, have you solved it?

**Comment by dh888222** [comment]
您的邮件已经成功发送。Your E-mail is successfully send to me.

**Comment by dh888222** [comment]
> I have the same problem, have you solved it?

Yes, the key problem which I have solved is using the wrong version of transformers(the version given is 4.41.1),I uninstalled it and update to 4.47.1.Then it works.

**Comment by lwj2001** [comment]
> > I have the same problem, have you solved it?
> 
> Yes, the key problem I solved was using the wrong version of Transformers (the version was 4.41.1). I uninstalled it and updated it to 4.47.1. Then it worked.

you are right!
